airports = {
    "RBA": {
        "name": "Rabat–Salé Airport",
        "city": "Rabat",
        "country": "Morocco",
        "latitude": 34.0515,
        "longitude": -6.7515,
    },
    "CMN": {
        "name": "Mohammed V International Airport",
        "city": "Casablanca",
        "country": "Morocco",
        "latitude": 33.3675,
        "longitude": -7.5899,
    },
    "TNG": {
        "name": "Tangier Ibn Battouta Airport",
        "city": "Tangier",
        "country": "Morocco",
        "latitude": 35.7269,
        "longitude": -5.9169,
    },
    "RAK": {
        "name": "Marrakesh Menara Airport",
        "city": "Marrakesh",
        "country": "Morocco",
        "latitude": 31.6069,
        "longitude": -8.0363,
    },
    "CDG": {
        "name": "Charles de Gaulle Airport",
        "city": "Paris",
        "country": "France",
        "latitude": 49.0097,
        "longitude": 2.5479,
    },
    "ORY": {
        "name": "Paris Orly Airport",
        "city": "Paris",
        "country": "France",
        "latitude": 48.7262,
        "longitude": 2.3652,
    },
    "NCE": {
        "name": "Nice Côte d'Azur Airport",
        "city": "Nice",
        "country": "France",
        "latitude": 43.6653,
        "longitude": 7.2150,
    },
    "LHR": {
        "name": "London Heathrow Airport",
        "city": "London",
        "country": "United Kingdom",
        "latitude": 51.4700,
        "longitude": -0.4543,
    },
    "MAD": {
        "name": "Adolfo Suárez Madrid-Barajas Airport",
        "city": "Madrid",
        "country": "Spain",
        "latitude": 40.4983,
        "longitude": -3.5676,
    },
    "JFK": {
        "name": "John F. Kennedy International Airport",
        "city": "New York",
        "country": "United States",
        "latitude": 40.6413,
        "longitude": -73.7781,
    },
}
