"""AeroFlight Suite database public API."""

from .database_manager import (
    create_database,
    insert_flight,
    insert_runway,
    flight_exists,
    get_all_flights,
    search_flights,
    advanced_search,
    filter_flights,
    sort_flights,
    get_statistics,
    get_all_runways,
    get_runways,
    get_runway,
    get_runway_performance,
    update_status,
    update_weather,
    update_flight_cost,
    update_distance,
    save_runway_performance,
    delete_flight_database,
    backup_database,
)

__all__ = [
    "create_database",
    "insert_flight",
    "insert_runway",
    "flight_exists",
    "get_all_flights",
    "search_flights",
    "advanced_search",
    "filter_flights",
    "sort_flights",
    "get_statistics",
    "get_all_runways",
    "get_runways",
    "get_runway",
    "get_runway_performance",
    "update_status",
    "update_weather",
    "update_flight_cost",
    "update_distance",
    "save_runway_performance",
    "delete_flight_database",
    "backup_database",
]
